name: nepal
favicon: null
layout_spectrum: 0.75321
typography_spectrum: 0.8891994168516248
title: Boeing 737 NG typerating worldwide
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a121d'
    - '#913345'
    - '#c4a593'
    - '#f3fbee'
    - '#cd5571'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
